//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fines
    {
        public int id { get; set; }
        public Nullable<int> the_user { get; set; }
        public Nullable<int> action { get; set; }
        public Nullable<System.DateTime> start_sate { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<decimal> fine { get; set; }
    
        public virtual tbl_action tbl_action { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
