//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_action()
        {
            this.tbl_fines = new HashSet<tbl_fines>();
        }
    
        public int id { get; set; }
        public Nullable<int> book { get; set; }
        public Nullable<int> the_user { get; set; }
        public Nullable<byte> employee { get; set; }
        public Nullable<System.DateTime> take_time { get; set; }
        public Nullable<System.DateTime> return_time { get; set; }
        public Nullable<System.DateTime> bring_time { get; set; }
        public Nullable<bool> action_status { get; set; }
    
        public virtual tbl_book tbl_book { get; set; }
        public virtual tbl_users tbl_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_fines> tbl_fines { get; set; }
        public virtual tbl_employers tbl_employers { get; set; }
    }
}
